"""phase2_core_schema

Revision ID: 45d931384951
Revises: 
Create Date: 2026-08-24 11:54:05.313207
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d931384951'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_action_id', sa.String(length=128), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('applied', 'conflict', 'failed', name='syncactionstatus', native_enum=False), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('conflict_detail', sa.JSON(), nullable=True),
    sa.Column('conflict_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_actions_action_type'), 'sync_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_sync_actions_client_action_id'), 'sync_actions', ['client_action_id'], unique=True)
    op.create_index(op.f('ix_sync_actions_status'), 'sync_actions', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('create', 'edit', 'approve', 'reject', 'sync', 'view', 'login', 'logout', name='auditaction', native_enum=False), nullable=False),
    sa.Column('diff_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log_entries', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_action'), 'audit_log_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_entity_id'), 'audit_log_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_entity_type'), 'audit_log_entries', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_user_id'), 'audit_log_entries', ['user_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('export_format', sa.Enum('geojson', 'shapefile', 'geopackage', 'csv', name='exportformat', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'complete', 'failed', name='exportstatus', native_enum=False), nullable=False),
    sa.Column('filter_params_json', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_status'), 'exports', ['status'], unique=False)
    op.create_table('imagery_tiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('crs', sa.String(length=50), nullable=True),
    sa.Column('bounds_wkt', sa.Text(), nullable=True),
    sa.Column('resolution_m', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('satellite', 'drone', 'aerial', 'other', name='tilesource', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'processed', 'failed', name='tilestatus', native_enum=False), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagery_tiles_status'), 'imagery_tiles', ['status'], unique=False)
    op.create_index(op.f('ix_imagery_tiles_uploaded_by_id'), 'imagery_tiles', ['uploaded_by_id'], unique=False)
    op.create_table('parcels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('geometry_wkt', sa.Text(), nullable=True),
    sa.Column('source_tile_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('zone', sa.String(length=200), nullable=True),
    sa.Column('jurisdiction', sa.String(length=200), nullable=True),
    sa.Column('workflow_status', sa.Enum('draft', 'validation_pending', 'validated', 'approved', 'rejected', name='parcelworkflowstatus', native_enum=False), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.String(length=50), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_tile_id'], ['imagery_tiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_jurisdiction'), 'parcels', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_parcels_source_tile_id'), 'parcels', ['source_tile_id'], unique=False)
    op.create_index(op.f('ix_parcels_workflow_status'), 'parcels', ['workflow_status'], unique=False)
    op.create_index(op.f('ix_parcels_zone'), 'parcels', ['zone'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tile_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.Enum('segmentation', 'change_detection', 'feature_extraction', name='jobtype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'complete', 'failed', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['imagery_tiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_tile_id'), 'processing_jobs', ['tile_id'], unique=False)
    op.create_table('building_footprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tile_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('parcel_id', sa.String(length=36), nullable=True),
    sa.Column('geometry_wkt', sa.Text(), nullable=True),
    sa.Column('feature_type', sa.Enum('building', 'road', 'water', 'vegetation', 'land', 'other', name='featuretype', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tile_id'], ['imagery_tiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_footprints_feature_type'), 'building_footprints', ['feature_type'], unique=False)
    op.create_index(op.f('ix_building_footprints_job_id'), 'building_footprints', ['job_id'], unique=False)
    op.create_index(op.f('ix_building_footprints_parcel_id'), 'building_footprints', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_building_footprints_tile_id'), 'building_footprints', ['tile_id'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parcel_a_id', sa.String(length=36), nullable=False),
    sa.Column('parcel_b_id', sa.String(length=36), nullable=False),
    sa.Column('conflict_type', sa.Enum('overlap', 'gap', 'boundary_mismatch', 'attribute_conflict', 'other', name='conflicttype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'ignored', name='conflictstatus', native_enum=False), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_a_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_b_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_conflict_type'), 'conflicts', ['conflict_type'], unique=False)
    op.create_index(op.f('ix_conflicts_parcel_a_id'), 'conflicts', ['parcel_a_id'], unique=False)
    op.create_index(op.f('ix_conflicts_parcel_b_id'), 'conflicts', ['parcel_b_id'], unique=False)
    op.create_index(op.f('ix_conflicts_status'), 'conflicts', ['status'], unique=False)
    op.create_table('validation_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=False),
    sa.Column('flag_type', sa.Enum('overlap', 'gap', 'self_intersection', 'confidence_low', 'boundary_mismatch', 'other', name='flagtype', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', 'critical', name='flagseverity', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_flags_flag_type'), 'validation_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_validation_flags_parcel_id'), 'validation_flags', ['parcel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_flags_parcel_id'), table_name='validation_flags')
    op.drop_index(op.f('ix_validation_flags_flag_type'), table_name='validation_flags')
    op.drop_table('validation_flags')
    op.drop_index(op.f('ix_conflicts_status'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_parcel_b_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_parcel_a_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_conflict_type'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_building_footprints_tile_id'), table_name='building_footprints')
    op.drop_index(op.f('ix_building_footprints_parcel_id'), table_name='building_footprints')
    op.drop_index(op.f('ix_building_footprints_job_id'), table_name='building_footprints')
    op.drop_index(op.f('ix_building_footprints_feature_type'), table_name='building_footprints')
    op.drop_table('building_footprints')
    op.drop_index(op.f('ix_processing_jobs_tile_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_parcels_zone'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_workflow_status'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_source_tile_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_jurisdiction'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_imagery_tiles_uploaded_by_id'), table_name='imagery_tiles')
    op.drop_index(op.f('ix_imagery_tiles_status'), table_name='imagery_tiles')
    op.drop_table('imagery_tiles')
    op.drop_index(op.f('ix_exports_status'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_audit_log_entries_user_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_entity_type'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_entity_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_action'), table_name='audit_log_entries')
    op.drop_index('ix_audit_entity', table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sync_actions_status'), table_name='sync_actions')
    op.drop_index(op.f('ix_sync_actions_client_action_id'), table_name='sync_actions')
    op.drop_index(op.f('ix_sync_actions_action_type'), table_name='sync_actions')
    op.drop_table('sync_actions')
    # ### end Alembic commands ###
